### ISSUE TITLE
In the first example

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/sql-book-insert-and-select#1]
It reads:
```sqlite> .schema
CREATE TABLE wizards(
  name STRING,
  age INTEGER
, color STRING);

But according to http://www.sqlite.org/datatype3.html .  STRING will register as the INTEGER type.  These STRINGs should be TEXT.

**Comment by garettarrowood** [comment]
So, STRING seems to work fine. And I guess the docs are wrong.  In that link, here is what it says under "2.2 Affinity Name Examples":

Note that a declared type of "FLOATING POINT" would give INTEGER affinity, not REAL affinity, due to the "INT" at the end of "POINT". And the declared type of "STRING" has an affinity of NUMERIC, not TEXT.

So, is it common to find mistakes in DOC files? Just part of the business of web development?

**Comment by AnnJohn** [comment]
Iceboxing for now
